### ISSUE TITLE
osx arm64 manual addition errors

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-forge-pinning-feedstock#2293]
Following the manual instructions [here](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/), I added the following:

```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
```

and I get this error in the build:

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
Adding in variants from /Users/runner/work/1/s/.ci_support/osx_arm64_python3.9.____cpython.yaml
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from /Users/runner/work/1/s/.ci_support/osx_arm64_python3.9.____cpython.yaml
Attempting to finalize metadata for pytype
INFO:conda_build.metadata:Attempting to finalize metadata for pytype
conda-forge/noarch        
conda-forge/osx-64        
Reloading output folder: /Users/runner/miniforge3/conda-bld
Users/runner/miniforge3/  
Users/runner/miniforge3/  
Mamba failed to solve:
 - cross-python_osx-arm64
 - python 3.9.* *_cpython
 - pybind11
 - clangxx_osx-arm64 11.*
 - cython
 - clang_osx-arm64 11.*
 - numpy 1.16.*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package numpy-1.16.0-py27_blas_openblash4251c03_1000 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
- 

```

This seems like a generic error that would be happening to all? The bot fwiw only adds the following:

```yaml
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
```

Maybe I am reading the manual instructions incorrectly, but it may be worth revisiting them and/or clarifying them. Thanks!

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by isuruf** [comment]
Need more info

**Comment by ngam** [comment]
1. go into a feedstock
2. copy exact (i.e. verbatim) instructions from the manual ([here](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/)):

`conda-forge.yml`:

```yaml
build_platform:
  osx_arm64: osx_64
test_on_native_only: true

```

`meta.yaml`:

```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
```

3. rerender
4. go to the azure log to see the error

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
Adding in variants from /Users/runner/work/1/s/.ci_support/osx_arm64_python3.9.____cpython.yaml
INFO:conda_build.variants:Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from /Users/runner/work/1/s/.ci_support/osx_arm64_python3.9.____cpython.yaml
Attempting to finalize metadata for pytype
INFO:conda_build.metadata:Attempting to finalize metadata for pytype
conda-forge/noarch        
conda-forge/osx-64        
Reloading output folder: /Users/runner/miniforge3/conda-bld
Users/runner/miniforge3/  
Users/runner/miniforge3/  
Mamba failed to solve:
 - cross-python_osx-arm64
 - python 3.9.* *_cpython
 - pybind11
 - clangxx_osx-arm64 11.*
 - cython
 - clang_osx-arm64 11.*
 - numpy 1.16.*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - package numpy-1.16.0-py27_blas_openblash4251c03_1000 requires python >=2.7,<2.8.0a0, but none of the providers can be installed
- 

```
