### ISSUE TITLE
Is a geotiff=1.7.1 migration needed?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/conda-forge-pinning-feedstock#2654]
### Comment:

I'm looking into dll-hell in the GDAL sphere and I think that geotiff=1.7.1 needs a migration done or its pin updated?  

I see this repo has
```
  geotiff:
    max_pin: x.x.x
...
geotiff:
  - '1.7'
```

I looked at the most recent bot logs and did not find any `geotiff` entries?  Does this need a manual migration or ?
