### ISSUE TITLE
Does one need to check that the ABI changed from X to Y.

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#3368]
### Comment:

I find the the question:

```
- [ ]  I checked that the ABI changed from X to Y.
```

doesn't really explain to the user what should happen if the ABI didn't change. 

The challenge is two fold:

1. The bot is kinda an "easy solution". It is also the "safe" solution.
2. Patching requires more manual (error prone) work that simply click merge on the bot rebuild.

So really, I would like to propose some clarification on what should happen if the pin doesn't change. I find "rebuilding" to be a good solution, even if the ABI doesn't change.

**Comment by hmaarrfk** [comment]
From https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3269 it seems that isuruf recommends:

1. Not merging the migrator.
2. Issuing a repo-data patch expanding the pinnings.

**Comment by hmaarrfk** [comment]
For example:

```python
        if record.get('timestamp', 0) < 1662860143000:
            if any(dep.startswith("libxml2 >=2.9") for dep in deps):
                _pin_looser(fn, record, "libxml2", upper_bound="2.11.0")
```

which was done as part of https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/316

**Comment by hmaarrfk** [comment]
For example to release the pin from `1.14.2` to allow compatibility with `1.14.3`

1. Make a repodata patch that includes variants of the build too
```
# While not guaranteed
# hdf5 1.14.2 and 1.14.3 have the same ABI
# https://gamma.hdfgroup.org/ftp/pub/outgoing/hdf5/prelim_reports/hdf5-1.14.2-vs-hdf5-1.14.3-1-interface_compatibility_report.html
if:
  has_depends: hdf5 >=1.14.2,<1.14.3.0a0?( *)
  timestamp_lt: 1702066879000

then:
  - loosen_depends:
      name: hdf5
      upper_bound: 1.14.4
```

2. Update the pin and any current migrations
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5243
