### ISSUE TITLE
max_pin and min_pin for packages.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#4]
@msarahan, what do you think about adding something like
```
pin_run_as_build:
  gmp:
    max_pin: x
    min_pin: x.x.x
```
This would mean that if gmp 6.1.2 was used at build time, then `>=6.1.2,<7` will be used at runtime, right?
