### ISSUE TITLE
Compiler for R/mingw

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#50]
How should we handle the compilers for R/MinGW ?

1.
```
- {{ compiler('c') }}   # [unix]
- mingw-toolchain   # [win]
```

2.
```
- {{ compiler('c') }}            # [unix]
- {{ compiler('mingw') }}   # [win]
```

3.

```
- {{ compiler('posix') }}
```

cc @conda-forge/core, @mingwandroid, @conda-forge/r-base

**Comment by isuruf** [comment]
ping

**Comment by mingwandroid** [comment]
Hi @isuruf, I have no time to work on this at present (and probably for the foreseeable future) if you want to have a go that'd be appreciated, you can follow our examples of how to do it at:

https://github.com/AnacondaRecipes/aggregate/tree/master/clang
and (probably more relevant due to GCC but well, it's all the same and all pretty simple stuff):
https://github.com/AnacondaRecipes/aggregate/tree/master/ctng-dbg-compilers-activation-feedstock/recipe

I'd be happy to review what you come up with though.

**Comment by mingwandroid** [comment]
One consideration is that at some point I would like to experiment with clang UCRT (with a custom hacked up clang GCC frontend) as a replacement for GCC on Windows so being able to template-ize that may be good, and so I do quite like 3 for our R packages.

**Comment by isuruf** [comment]
> You removed compiler('posix') when you edited your comment replacing it with - {{ compiler('r_base_c') }}, but there is a valid use-case for compiler('posix_c/cxx') on Windows, this would be the msys2 posix compiler which is very closely related to Cygwin's compiler, i.e. the one that links everything to the posix emulation layer (which is not what m2w64-toolchain does; system-wise, it only links to MS provided system DLLs - or to its own runtimes which also only link to MS provided system DLLs).

I thought that would be a different conversation unrelated to this, so that's why I removed it.

**Comment by mingwandroid** [comment]
Well, it all ties in really, but spin it out of you wish.

It'd be fantastic not to be opinionated about the POSIX-y build env. required to build some of our packages though and to leave that as a tweakable config parameter in a single file (which can be overridden by a file closer to the package for when one works but the other doesn't).

Of course making `WSL` work would require some effort, and I do not expect it is going to be a high priority for the `Anaconda Distribution` team since we have something that works already.

**Comment by isuruf** [comment]
For the 3rd point, we would have to add,
```yaml
r_base_c_compiler:
  - toolchain_c                # [unix]
  - m2w64_toolchain            # [win]
r_base_cxx_compiler:
  - toolchain_cxx              # [unix]
  - m2w64_toolchain            # [win]
r_base_fortran_compiler:
  - toolchain_fort             # [unix]
  - m2w64_toolchain            # [win]
```

and we could use
```yaml
- {{ compiler('r_base_c') }}
- {{ compiler('r_base_cxx') }}
- {{ compiler('r_base_fortran') }}
```

**Comment by mingwandroid** [comment]
Sure that's a good start, however you may want to take advantage of strong run_exports to automate your language runtime library run requirements out automatically.

This is one of the nicest features of the new stuff imho.

**Comment by mingwandroid** [comment]
To do this you'd make a metapackage for exact compiler that run requires the toolchains and add the appropriate (strong) run exports.

**Comment by isuruf** [comment]
`toolchain_c` do have `run_exports`, https://github.com/conda-forge/toolchain-feedstock/blob/master/recipe/meta.yaml#L31

`m2w64-toolchain` don't need any runtimes right?

**Comment by mingwandroid** [comment]
You want 3 new toolchain_mingw64_{c,cxx,fortran} packages here each run requiring m2w64_toolchain but each adding only the minimum necessary run_exports (please check the msys2 channel for the correct names).

**Comment by isuruf** [comment]
`m2w64-gcc-libs` is the runtime library which has runtimes
```
        - msys2-conda-epoch >=20160418
        - m2w64-gmp
        - m2w64-gcc-libs-core
        - m2w64-gcc-libgfortran
        - m2w64-libwinpthread-git
```

So, `m2w64-libwinpthread-git`, `m2w64-gcc-libs-core` for all compilers and `m2w64-gcc-libgfortran` for Fortran ? I don't know what `msys2-conda-epoch` does and I thought `m2w64-gmp` was needed only for constant folding, not sure though.

**Comment by isuruf** [comment]
`m2w64-gmp`, `m2w64-libwinpthread-git` and `msys2-conda-epoch` are all dependencies of `m2w64-gcc-libs-core`, so something like below might work,

```yaml
  - name: toolchain_mingw_c_{{ target_platform }}
    run_exports:
      strong:
        - m2w64-gcc-libs-core

  - name: toolchain_mingw_cxx_{{ target_platform }}
    run_exports:
      strong:
        - m2w64-gcc-libs-core

  - name: toolchain_mingw_fort_{{ target_platform }}
    run_exports:
      strong:
        - m2w64-gcc-libs-core
        - m2w64-gcc-libgfortran
```
