### ISSUE TITLE
curl/libcurl getting pinned too specifically

### ISSUE THREAD

**Issue by xylar** [conda-forge/conda-forge-pinning-feedstock#537]
I believe that #157 incorrectly specified both major an minor versions for curl and libcurl even though they have:
```
 pin_run_as_build:
  curl:
    max_pin: x
  libcurl:
    max_pin: x
```
This seems to be causing problems in a rebuild of `nco`:  https://github.com/conda-forge/nco-feedstock/pull/108
