### ISSUE TITLE
Adding `libblst` to the global pinnings

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#6623]
As `libblst` is starting to be used in other packages, we should add `run_exports` to it ( https://github.com/conda-forge/libblst-feedstock/issues/2 ) and add it to the global pinning with some initial version. That will help provide migration support when it is needed.

cc @conda-forge/libblst

**Comment by step21** [comment]
sth like 0.3.x as pinning?

**Comment by jakirkham** [comment]
As `libblst` now [uses `run_exports` with `max_pin='x.x'`]( https://github.com/conda-forge/libblst-feedstock/blob/f22a4ee14985a4dfac38594a6147e7ef74e11deb/recipe/meta.yaml#L29-L32 ), we should adopt similar syntax here

Namely would add

```yaml
pin_run_as_build:
  ...
  # Drop when `libblst` reaches `0.4`
  libblst:
    max_pin: x.x
  ...
...
libblst:
  - '0.3'
```
