### ISSUE TITLE
inconsistent rust compiler pinnings

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/conda-forge-pinning-feedstock#875]
Apologies if this is the wrong place to report this, but this is the best place I could come up with.

I have been looking at package build errors and most recently found [`tokenizers`](https://github.com/conda-forge/tokenizers-feedstock).

The recipe dependencies are simple enough:
```yaml
requirements:
  build:
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools-rust
    - setuptools
  run:
    - python
    - libgcc-ng                                                  # [linux]
```
and in the past this did work.
At the moment [all pull requests fail](https://github.com/conda-forge/tokenizers-feedstock/pulls), 

Looking specifically at the most recent [version update PR from 3 days ago](https://github.com/conda-forge/tokenizers-feedstock/pull/7) the Python 3.6/Linux build fails setting up the build environment. Unfortunately the conda resolution errors are utterly meaningless to me. Thanks to mamba I could make some sense of it though. The relevant bit appears to be around
```
Package rust conflicts for:
rust_linux-64==1.29.0=he6710b0_0 -> rust
rust==1.49.0.dev20201014=hd18ef5c_0
```

The feedstock [aims to use rust 1.29](https://github.com/conda-forge/tokenizers-feedstock/blob/112bf2e0cc7a96ae71a85aed12774221887b5c0a/.ci_support/linux_python3.6.____cpython.yaml#L15-L16):
```yaml
channel_sources:
- conda-forge/label/rust_dev,conda-forge,defaults
(..)
rust_compiler:
- rust
rust_compiler_version:
- 1.29.0
```
but then, for whatever reason, comes up with the idea of pulling in `rust_linux-64`, [which doesn't exist for 1.29](https://anaconda.org/conda-forge/rust_linux-64/files).

I don't know enough to debug this further.
